NAME="glad"
VERS="2.0.8"
DESC="Generator for loading Vulkan, OpenGL, EGL, GLES, and GLX contexts"
CATG="lib graphics"
UPST="https://github.com/Dav1dde/glad.git"
DEPS=()

SOURCE="https://github.com/Dav1dde/glad/archive/v$VERS/glad-$VERS.tar.gz"
EXTRA=()

2b() {

with pip

pipb
NAME=glad2 pipi

}
