NAME="acl"
VERS="2.3.2"
DESC="Access Control Lists"
UPST="https://git.savannah.nongnu.org/git/acl.git"

SOURCE="https://download.savannah.gnu.org/releases/acl/acl-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

mk distclean

m32=1
cfg
mk
mi

}
