NAME="scdoc"
VERS="1.11.3"
DESC="Small man page generator"
CATG="doc"
UPST="https://git.sr.ht/~sircmpwn/scdoc"

SOURCE="https://git.sr.ht/~sircmpwn/$NAME/archive/$VERS.tar.gz"

2b() {

mk PREFIX=/usr LDFLAGS="$LDFLAGS"
mi PREFIX=/usr

}
