NAME="groff"
VERS="1.23.0"
DESC="Programs for processing and formatting text and images"

SOURCE="https://ftp.gnu.org/gnu/groff/groff-$VERS.tar.gz"
EXTRA=()

2b() {

PAGE="letter" b-cfg
b-make
b-mi

}
