NAME="lzip"
VERS="1.25"
DESC="A lossless file compressor based on the LZMA algorithm"

SOURCE="http://download.savannah.gnu.org/releases/lzip/lzip-$VERS.tar.gz"
EXTRA=()

2b() {

b-cfg
b-make
b-mi

}
