# TODO: Test this once freedesktop is back online
NAME="libdisplay-info"
VERS="0.2.0"
DESC="EDID and DisplayID library"
CATG="lib"
UPST="https://gitlab.freedesktop.org/emersion/libdisplay-info.git"
DEPS=(
    "hwdata"
)

SOURCE="https://gitlab.freedesktop.org/emersion/$NAME/-/releases/$VERS/downloads/$NAME-$VERS.tar.xz"
EXTRA=()

2b() {

with meson ninja

ms
nj
ni

}
