NAME="check"
VERS="0.15.2"
DESC="Unit testing framework for C"

SOURCE="https://github.com/libcheck/check/releases/download/$VERS/check-$VERS.tar.gz"
EXTRA=()

2b() {

b-cfg
b-make
b-mi

b-32cfg
b-make
b-32mi

}
