NAME="check"
VERS="0.15.2"
DESC="Unit testing framework for C"
UPST="https://github.com/libcheck/check.git"

SOURCE="https://github.com/libcheck/check/releases/download/$VERS/check-$VERS.tar.gz"
EXTRA=()

2b() {

cfg
mk
mi

m32=1
cfg
mk
mi

}
