NAME="patch"
VERS="2.8"
CATG="core"
DESC="Utility to apply patch files to source files"
UPST="https://git.savannah.gnu.org/git/patch.git"

SOURCE="https://ftp.gnu.org/gnu/patch/patch-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

}