NAME="imlib2"
VERS="1.12.4"
DESC="Image loading and rendering library"
CATG="lib img"
UPST="https://git.enlightenment.org/old/legacy-imlib2.git"
DEPS=()

SOURCE="https://downloads.sourceforge.net/project/enlightenment/imlib2-src/$VERS/imlib2-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

}