NAME="xdg-utils"
VERS="1.2.1"
DESC="Command line tools that assist applications with a variety of desktop integration tasks"
CATG="cli util"
UPST="https://gitlab.freedesktop.org/xdg/xdg-utils.git"
DEPS=(
    "xmlto"  # with lynx (or others)
    "xprop"
    "xset"
    "o^dbus"
)

SOURCE="https://gitlab.freedesktop.org/xdg/$NAME/-/archive/v$VERS/$NAME-v$VERS.tar.gz"
EXTRA=()

2b() {

cfg
mk
mi

}
