NAME="btop"
VERS="1.4.0"
DESC="System resource monitor"
CATG="tui utils"
UPST="https://github.com/aristocratos/btop.git"
DEPS=()

SOURCE="https://github.com/aristocratos/btop/archive/v$VERS/btop-$VERS.tar.gz"
EXTRA=()

2b() {

mk
mi PREFIX=/usr

}
