NAME="dbus"
VERS="1.16.0"
DESC="Freedesktop.org message bus system"
UPST="https://gitlab.freedesktop.org/dbus/dbus.git"
DEPS=(
    "xorg/@libs" # TODO: Make this work lol
)

SOURCE=""
EXTRA=()

2b() {

}
