NAME="libogg"
VERS="1.3.5"
DESC="Ogg container format libraries"
UPST="https://github.com/xiph/ogg.git"

SOURCE="https://downloads.xiph.org/releases/ogg/libogg-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

mk distclean
m32=1

cfg
mk
mi

}
