NAME="libidn2"
VERS="2.3.8"
DESC="Library for working with internationalized domain names"
UPST="https://gitlab.com/libidn/libidn2.git"

SOURCE="https://ftp.gnu.org/gnu/libidn/$NAME-$VERS.tar.gz"
EXTRA=()

2b() {

cfg
mk
mi

mk distclean
m32=1

cfg
mk
mi

}