NAME="libidn2"
VERS="2.3.7"
DESC="Library for working with internationalized domain names"
UPST="https://gitlab.com/libidn/libidn2.git"

SOURCE="https://ftp.gnu.org/gnu/libidn/$NAME-$VERS.tar.gz"
EXTRA=()

2b() {

b-cfg
b-make
b-mi

b-make distclean

b-32cfg
b-make
b-32mi

}
