NAME="iso-codes"
VERS="4.17.0"
DESC="Database of country, language, and currency names"
CATG="lib"
UPST="https://salsa.debian.org/iso-codes-team/iso-codes.git"
DEPS=()

SOURCE="https://salsa.debian.org/$NAME-team/$NAME/-/archive/v$VERS/$NAME-v$VERS.tar.gz"
EXTRA=()

2b() {

cfg
mk

mi LN_S='ln -sfn'

}
