NAME="automake"
VERS="1.17"
DESC="Programs for generating Makefiles for use with Autoconf"
UPST="https://git.savannah.gnu.org/git/automake.git"

SOURCE="https://ftp.gnu.org/gnu/automake/automake-$VERS.tar.xz"
EXTRA=()

2b() {

./configure --prefix=/usr
b-make
b-mi

}
