NAME="automake"
VERS="1.17"
DESC="Programs for generating Makefiles for use with Autoconf"

SOURCE="https://ftp.gnu.org/gnu/automake/automake-$VERS.tar.xz"
EXTRA=()

2b() {

DS=1 b-cfg
b-make
b-mi

}
