NAME="rofi"
VERS="1.7.8"
DESC="Application launcher, window switcher, and dmenu replacement"
CATG="gui utils"
UPST="https://github.com/davatorium/rofi.git"
DEPS=(
    "pango"
    "cairo"
    "xcb-util"
    "xcb-util-wm"
    "xcb-util-cursor"
)

SOURCE="https://github.com/davatorium/rofi/releases/download/$VERS/rofi-$VERS.tar.xz"
EXTRA=()

2b() {

with meson ninja

ms
nj
ni

}
