NAME="dejagnu"
VERS="1.6.3"
DESC="Framework for running GNU test suites written in expect"

SOURCE="https://ftp.gnu.org/gnu/dejagnu/dejagnu-$VERS.tar.gz"
EXTRA=()

2b() {

mkdir -pv build
cd        build

DS=1 b-cfg

b-mi

}

#d fixed .uv.toml
