NAME="libunistring"
VERS="1.3"
DESC="Library for manipulating Unicode strings"
UPST="https://git.savannah.gnu.org/git/libunistring.git"

SOURCE="https://ftp.gnu.org/gnu/$NAME/$NAME-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

mk distclean
m32=1

cfg
mk
mi

}
