NAME="libunistring"
VERS="1.3"
DESC="Library for manipulating Unicode strings"
UPST="https://git.savannah.gnu.org/git/libunistring.git"

SOURCE="https://ftp.gnu.org/gnu/$NAME/$NAME-$VERS.tar.xz"
EXTRA=()

2b() {

b-cfg
b-make
b-mi

b-make distclean

b-32cfg
b-make
b-32mi

}
