NAME="gperf"
VERS="3.1"
CATG="core"
DESC="Perfect hash function generator"
UPST="https://git.savannah.gnu.org/git/gperf.git"

SOURCE="https://ftp.gnu.org/gnu/gperf/gperf-$VERS.tar.gz"
EXTRA=()

2b() {

cfg
mk
mi

}
