NAME="gperf"
VERS="3.1"
DESC="Perfect hash function generator"
UPST="https://git.savannah.gnu.org/git/gperf.git"

SOURCE="https://ftp.gnu.org/gnu/gperf/gperf-$VERS.tar.gz"
EXTRA=()

2b() {

./configure --prefix=/usr
b-make
b-mi

}
