NAME="libyaml"
VERS="0.2.5"
DESC="C library for parsing and emitting YAML"
CATG="dev"
UPST="https://github.com/yaml/libyaml.git"
VCMD="git ls-remote --tags --refs '$UPST' | sed 's@.*/@@' | grep -v '[a-z]' | tail -n1"
DEPS=()

SOURCE="https://github.com/yaml/libyaml/releases/download/$VERS/yaml-$VERS.tar.gz"
EXTRA=()

2b() {

cfg
mk
mi

}
