NAME="libyaml"
VERS="0.2.5"
DESC="C library for parsing and emitting YAML"
CATG="dev"
UPST="https://github.com/yaml/libyaml.git"
DEPS=()

SOURCE="https://github.com/yaml/libyaml/releases/download/0.2.5/yaml-0.2.5.tar.gz"
EXTRA=()

2b() {

cm
mk
mi

}
