NAME="libassuan"
VERS="3.0.2"
DESC="Assuan IPC library"
CATG="lib"
UPST="https://github.com/gpg/libassuan.git"
DEPS=(
    "libgpg-error"
)

SOURCE="https://www.gnupg.org/ftp/gcrypt/libassuan/libassuan-$VERS.tar.bz2"
EXTRA=()

2b() {

cfg
mk
mi

}
