NAME="i3ipc"
VERS="2.2.1"
DESC="i3 IPC library"
CATG="lib wm"
UPST="https://github.com/altdesktop/i3ipc-python.git"
DEPS=(
    "setuptools"
    "python"
    "i3"
)

SOURCE="https://github.com/altdesktop/i3ipc-python/archive/refs/tags/v$VERS.tar.gz"
EXTRA=()

2b() {

with pip

pipb
pipi

}
