NAME="alsa-lib"
VERS="1.2.13"
DESC="ALSA library"
UPST="https://github.com/alsa-project/alsa-lib.git"

SOURCE="https://www.alsa-project.org/files/pub/lib/alsa-lib-$VERS.tar.bz2"
EXTRA=()

2b() {

cfg
mk
mi

mk distclean

m32=1
cfg
mk
mi

}
