NAME="libass"
VERS="0.17.3"
DESC="Library for the ASS subtitle format"
CATG="lib"
UPST="https://github.com/libass/libass.git"
DEPS=(
    "freetype"
    "fribidi"
    "fontconfig"
    "nasm"
)

SOURCE="https://github.com/libass/libass/releases/download/$VERS/libass-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

}
