NAME="libgudev"
VERS="238"
DESC="GObject bindings for libudev"
CATG="lib"
UPST="https://github.com/GNOME/libgudev.git"
DEPS=(
    "glib"
)

SOURCE="https://download.gnome.org/sources/$NAME/$VERS/$NAME-$VERS.tar.xz"
EXTRA=()

2b() {

with meson ninja

ms
nj
ni

}
