NAME="libglvnd"
VERS="1.7.0"
DESC="GL Vendor-Neutral Dispatch library"
CATG="lib graphics"
UPST="https://gitlab.freedesktop.org/glvnd/libglvnd.git"
DEPS=(
    "libxext",
    "libx11",
    "xorgproto",
    "meson",
    "python",
)

SOURCE="https://gitlab.freedesktop.org/glvnd/libglvnd/-/archive/v$VERS/libglvnd-v$VERS.tar.gz"
EXTRA=()

2b() {

with meson ninja

ms
nj
ni

m32=1
cd ..

ms
nj
ni

}
