NAME="libglvnd"
VERS="1.7.0"
DESC="GL Vendor-Neutral Dispatch library"
CATG="lib graphics"
UPST="https://gitlab.freedesktop.org/glvnd/libglvnd.git"
DEPS=(
    libxext
    libx11
    xorgproto
    meson
    python
)

SOURCE=""
EXTRA=()

2b() {

}
