NAME="libexif"
VERS="0.6.25"
DESC="Library for parsing, editing, and saving EXIF data"
CATG="lib"
UPST="https://github.com/libexif/libexif.git"
DEPS=()

SOURCE="https://github.com/libexif/libexif/releases/download/v$VERS/libexif-$VERS.tar.bz2"
EXTRA=()

2b() {

cfg
mk
mi

}
