NAME="setuptools"
VERS="78.0.2"
CATG="core"
DESC="Tool for downloading, building, installing, upgrading, and uninstalling Python pacakges"
UPST="https://github.com/pypa/setuptools.git"

SOURCE="https://pypi.org/packages/source/s/setuptools/setuptools-$VERS.tar.gz"
EXTRA=()

2b() {

with pip

pipb
NAME="$NAME" pipi

}