NAME="setuptools"
VERS="75.6.0"
DESC="Tool for downloading, building, installing, upgrading, and uninstalling Python pacakges"
UPST="https://github.com/pypa/setuptools.git"

SOURCE="https://pypi.org/packages/source/s/setuptools/setuptools-$VERS.tar.gz"
EXTRA=()

2b() {

b-pipbuild
NAME="$NAME" b-pipinstall

}
