NAME="setuptools"
VERS="75.8.0"
DESC="Tool for downloading, building, installing, upgrading, and uninstalling Python pacakges"

SOURCE="https://pypi.org/packages/source/s/setuptools/setuptools-$VERS.tar.gz"
EXTRA=()

2b() {

b-pipbuild
NAME="$NAME" b-pipinstall

}
