NAME="libtiff"
VERS="4.7.0"
DESC="Libraries and utilities for handling TIFF images"
CATG="lib util"
UPST="https://gitlab.com/libtiff/libtiff.git"
DEPS=(
    "cmake"
    "o^libjpeg-turbo"
    "o^libwebp"
)

SOURCE="https://download.osgeo.org/libtiff/tiff-$VERS.tar.gz"
EXTRA=()

2b() {

with cmake ninja

cm
nj
ni

}
