NAME="wayland-protocols"
VERS="1.42"
DESC="Additional protocols expanding Wayland functionality"
UPST="https://gitlab.freedesktop.org/wayland/wayland-protocols.git"

SOURCE="https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/$VERS/downloads/wayland-protocols-$VERS.tar.xz"
EXTRA=()

2b() {

with meson ninja

ms
nj
ni

}