NAME="wayland-protocols"
VERS="1.40"
DESC="Additional protocols expanding Wayland functionality"
UPST="https://gitlab.freedesktop.org/wayland/wayland-protocols.git"

SOURCE="https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/$VERS/downloads/wayland-protocols-$VERS.tar.xz"
EXTRA=()

2b() {

mkdir -pv build
cd        build

CP=.. b-ms
b-ninja
b-ni

}
