NAME="nvim"
VERS="0.10.3"
DESC="Continuation and extension of Vim"
UPST="https://github.com/neovim/neovim.git"

SOURCE="https://github.com/neovim/neovim/archive/refs/tags/v0.10.3.tar.gz"
EXTRA=()

2b() {

b-make CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=/usr"
b-mi

}
