NAME="nvim"
VERS="0.11.0"
DESC="Continuation and extension of Vim"
UPST="https://github.com/neovim/neovim.git"

SOURCE="https://github.com/neovim/neovim/archive/refs/tags/v$VERS.tar.gz"
EXTRA=()

2b() {

mk CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX=/usr"
mi

}
