NAME="libpipeline"
VERS="1.5.8"
DESC="Library for manipulating subprocess pipelines"
UPST="https://gitlab.com/libpipeline/libpipeline.git"

SOURCE="https://download.savannah.gnu.org/releases/libpipeline/libpipeline-$VERS.tar.gz"
EXTRA=()

2b() {

b-cfg
b-make
b-mi

}
