NAME="libpipeline"
VERS="1.5.8"
DESC="Library for manipulating subprocess pipelines"
UPST="https://gitlab.com/libpipeline/libpipeline.git"
VCMD="git ls-remote --tags --refs '$UPST' | sed 's@.*/@@' | grep -Ev '^2.+' | tail -n1"

SOURCE="https://download.savannah.gnu.org/releases/libpipeline/libpipeline-$VERS.tar.gz"
EXTRA=()

2b() {

b-cfg
b-make
b-mi

}
