NAME="entr"
VERS="5.7"
DESC="Run arbitrary commands on file change"
UPST="https://github.com/eradman/entr.git"

SOURCE="https://github.com/eradman/entr/archive/refs/tags/$VERS.tar.gz"
EXTRA=()

2b() {

export PREFIX='/usr'
b-cfg
b-mi

}
