NAME="neofetch"
VERS="7.1.0"
DESC="Famous (now unmaintained) fetch script written in bash"
UPST="https://github.com/dylanaraps/neofetch.git"

SOURCE="https://github.com/dylanaraps/neofetch/archive/refs/tags/$VERS.tar.gz"
EXTRA=()

2b() {

b-mi

}
