NAME="libtasn1"
VERS="4.20.0"
DESC="Library for encoding and decoding DER/BER data"
UPST="https://gitlab.com/gnutls/libtasn1.git"

SOURCE="https://ftp.gnu.org/gnu/$NAME/$NAME-$VERS.tar.gz"
EXTRA=()

2b() {

cfg
mk
mi

mk distclean
m32=1

cfg
mk
mi

}
