NAME="nghttp2"
VERS="1.64.0"
DESC="Implementation of HTTP/2"
UPST="https://github.com/$NAME/$NAME.git"

SOURCE="https://github.com/$NAME/$NAME/releases/download/v$VERS/$NAME-$VERS.tar.xz"
EXTRA=()

2b() {

b-cfg --enable-lib-only
b-make
b-mi

}
