NAME="luajit"
VERS="eec7a8016c3381b949b5d84583800d05897fa960"
DESC="Just-In-Time Lua compiler"
CATG="lang"
UPST="https://github.com/LuaJIT/LuaJIT.git"
DEPS=()

SOURCE="https://github.com/LuaJIT/LuaJIT/archive/$VERS.tar.gz"
EXTRA=()

2b() {

mk PREFIX=/usr amalg
mi PREFIX=/usr

rm -vf "$D"/usr/lib/libluajit-*.a

}