NAME="sendme"
VERS="0.23.0"
DESC="Stupid easy file transferring"
UPST="https://github.com/n0-computer/sendme.git"

SOURCE="https://github.com/n0-computer/sendme/archive/refs/tags/v$VERS.tar.gz"
EXTRA=()

2b() {

with rust

cbr
install -vDm755 target/release/sendme "$D/usr/bin/sendme"

}