NAME="markupsafe"
VERS="3.0.2"
DESC="Python module implementing an XML/HTML/XHTML Markup safe string"

SOURCE="https://pypi.org/packages/source/M/MarkupSafe/markupsafe-$VERS.tar.gz"
EXTRA=()

2b() {

b-pipbuild
b-pipinstall "$NAME"

}
