NAME="markupsafe"
VERS="3.0.2"
DESC="Python module implementing an XML/HTML/XHTML Markup safe string"
UPST="https://github.com/pallets/markupsafe.git"

SOURCE="https://pypi.org/packages/source/M/MarkupSafe/markupsafe-$VERS.tar.gz"
EXTRA=()

2b() {

with pip

pipb
pipi "$NAME"

}
