NAME="flit-core"
VERS="3.10.1"
DESC="Tool for building distributable Python modules"

SOURCE="https://pypi.org/packages/source/f/flit-core/flit_core-$VERS.tar.gz"
EXTRA=()

2b() {

b-pipbuild
NAME="${NAME//-/_}" b-pipinstall

}
