NAME="libxslt"
VERS="1.1.43"
DESC="XSLT libraries extending libxml2"
CATG="lib"
UPST="https://github.com/GNOME/libxslt.git"
DEPS=(
    "libxml2"
    "r^docbook-xml4"
    "r^docbook-xsl-nons"
)

SOURCE="https://download.gnome.org/sources/libxslt/${VERS%.*}/libxslt-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

}