NAME="wheel"
VERS="0.46.0"
CATG="core"
DESC="Python library for the Python wheel packaging standard"
UPST="https://github.com/pypa/wheel.git"

SOURCE="https://pypi.org/packages/source/w/wheel/wheel-$VERS.tar.gz"
EXTRA=()

2b() {

with pip

pipb
NAME="$NAME" pipi

}