NAME="wheel"
VERS="0.45.1"
DESC="Python library for the Python wheel packaging standard"

SOURCE="https://pypi.org/packages/source/w/wheel/wheel-$VERS.tar.gz"
EXTRA=()

2b() {

b-pipbuild
NAME="$NAME" b-pipinstall

}
