NAME="wheel"
VERS="0.45.1"
DESC="Python library for the Python wheel packaging standard"
UPST="https://github.com/pypa/wheel.git"

SOURCE="https://pypi.org/packages/source/w/wheel/wheel-$VERS.tar.gz"
EXTRA=()

2b() {

with pip

pipb
NAME="$NAME" pipi

}
