NAME="libnsl"
VERS="2.0.1"
DESC="Public client interface library for NIS(YP)"
CATG="lib net"
UPST="https://github.com/thkukuk/libnsl.git"
DEPS=(
    libtirpc
)

SOURCE="https://github.com/thkukuk/libnsl/releases/download/v$VERS/libnsl-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

}
