NAME="lfs-bootscripts"
VERS="20240825"
DESC="A set of scripts to start/stop the LFS system at bootup/shutdown"

SOURCE="https://www.linuxfromscratch.org/lfs/downloads/development/lfs-bootscripts-$VERS.tar.xz"
EXTRA=()

2b() {

b-mi

}
