NAME="lfs-bootscripts"
VERS="20240825"
DESC="A set of scripts to start/stop the LFS system at bootup/shutdown"
UPST="https://www.linuxfromscratch.org/~thomas/multilib-m32/chapter09/bootscripts.html"
VCMD="curl -s '$UPST' | grep LFS-Bootscripts- | tail -n1 | cut -d- -f3"

SOURCE="https://www.linuxfromscratch.org/lfs/downloads/development/lfs-bootscripts-$VERS.tar.xz"
EXTRA=()

2b() {

b-mi

}
