NAME="pyparsing"
VERS="3.2.3"
DESC="General parsing module for Python"
CATG="lib"
UPST="https://github.com/pyparsing/pyparsing.git"
DEPS=(
    "python"
)

SOURCE="https://files.pythonhosted.org/packages/source/p/pyparsing/pyparsing-$VERS.tar.gz"
EXTRA=()

2b() {

pipb
pipi

}
