NAME="pyparsing"
VERS="3.2.3"
DESC="General parsing module for Python"
CATG="lib"
UPST="https://github.com/pyparsing/pyparsing.git"
VCMD="git ls-remote --tags --refs $UPST | sed 's@.*/@@' | cut -d_ -f2- | grep -v '[a-Z]' | sort -V | tail -n1"
DEPS=(
    "python"
)

SOURCE="https://files.pythonhosted.org/packages/source/p/pyparsing/pyparsing-$VERS.tar.gz"
EXTRA=()

2b() {

with pip

pipb
pipi

}
