NAME="autoconf"
VERS="2.72"
DESC="Programs to produce shell scripts to automatically configure source code"
UPST="https://git.savannah.gnu.org/git/autoconf.git"

SOURCE="https://ftp.gnu.org/gnu/autoconf/autoconf-$VERS.tar.xz"
EXTRA=()

2b() {

DS=1 b-cfg
b-make
b-mi

}
