NAME="whois"
VERS="5.5.23"
DESC="Tool to query domain name information"
UPST="https://github.com/rfc1036/whois"

SOURCE="https://github.com/rfc1036/whois/archive/v$VERS/whois-$VERS.tar.gz"
EXTRA=()

2b() {

b-make
b-make prefix=/usr DESTDIR="$D" install

}
