NAME="whois"
VERS="5.6.0"
DESC="Tool to query domain name information"
UPST="https://github.com/rfc1036/whois"

SOURCE="https://github.com/rfc1036/whois/archive/v$VERS/whois-$VERS.tar.gz"
EXTRA=()

2b() {

mk
mi prefix=/usr

}