NAME="ansifilter"
VERS="2.21"
DESC="ANSI sequence filter"
CATG="cli utils"
UPST="https://gitlab.com/saalen/ansifilter.git"
DEPS=()

SOURCE="https://gitlab.com/saalen/ansifilter/-/archive/$VERS/ansifilter-$VERS.tar.bz2"
EXTRA=()

2b() {

mk
mi

rm -vf "$D"/usr/share/doc/ansifilter/{COPYING,INSTALL}

}
