NAME="efivar"
VERS="39"
DESC="Tools and libraries for EFI variable manipulation"
UPST="https://github.com/rhboot/efivar.git"

SOURCE="https://github.com/rhboot/efivar/archive/39/efivar-39.tar.gz"
EXTRA=()

2b() {

b-make ENABLE_DOCS=0
b-mi LIBDIR=/usr/lib ENABLE_DOCS=0

}
