NAME="libgpg-error"
VERS="1.51"
DESC="Library defining common error values for GPG components"
CATG=""
UPST="https://github.com/gpg/libgpg-error.git"
DEPS=()

SOURCE="https://www.gnupg.org/ftp/gcrypt/$NAME/$NAME-$VERS.tar.gz"
EXTRA=()

2b() {

cfg
mk
mi

}
