NAME="psmisc"
VERS="23.7"
DESC="Process monitoring utilities"
UPST="https://gitlab.com/psmisc/psmisc.git"

SOURCE="https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-$VERS.tar.xz"
EXTRA=()

2b() {

DS=1 b-cfg
b-make
b-mi

}
