NAME="psmisc"
VERS="23.7"
CATG="core"
DESC="Process monitoring utilities"
UPST="https://gitlab.com/psmisc/psmisc.git"

SOURCE="https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

}
