NAME="pfetch"
VERS="0.6.0"
DESC="Pretty (and unmaintained) fetch script written in POSIX sh"
UPST="https://github.com/dylanaraps/pfetch.git"

SOURCE="https://github.com/dylanaraps/pfetch/archive/refs/tags/$VERS.tar.gz"
EXTRA=()

2b() {

b-mi

}
