NAME="bison"
VERS="3.8.2"
CATG="core"
DESC="Parser generator"
UPST="https://git.savannah.gnu.org/git/bison.git"

SOURCE="https://ftp.gnu.org/gnu/bison/bison-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

}
