NAME="bison"
VERS="3.8.2"
DESC="Parser generator"
UPST="https://git.savannah.gnu.org/git/bison.git"

SOURCE="https://ftp.gnu.org/gnu/bison/bison-$VERS.tar.xz"
EXTRA=()

2b() {

b-cfg --prefix=/usr
b-make
b-mi

}
