NAME="time"
VERS="1.9"
DESC="Utility for monitoring a program's use of system resources"
UPST="https://git.savannah.gnu.org/git/time.git"

SOURCE="https://ftp.gnu.org/gnu/time/time-$VERS.tar.gz"
EXTRA=()

2b() {

b-cfg
b-make
b-mi

}
