NAME="opus"
VERS="1.5.2"
DESC="Lossy audio compression format, well suited to transmission"
UPST="https://github.com/xiph/opus.git"

SOURCE="https://github.com/xiph/opus/releases/download/v$VERS/opus-$VERS.tar.gz"
EXTRA=()

2b() {

with meson ninja

ms
nj
ni

cd ..
m32=1

ms
nj
ni

}
