NAME="diffutils"
VERS="3.11"
CATG="core"
DESC="Programs to show the differences between files or directories"
UPST="https://git.savannah.gnu.org/git/diffutils.git"

SOURCE="https://ftp.gnu.org/gnu/diffutils/diffutils-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

}
