NAME="bubblewrap"
VERS="0.11.0"
DESC="Unprivileged sandboxing tool"
CATG=""
UPST="https://github.com/containers/bubblewrap.git"
DEPS=()

SOURCE="https://github.com/containers/$NAME/releases/download/v$VERS/$NAME-$VERS.tar.xz"
EXTRA=()

KCFG=(
    "namespaces=*"
    "user_ns=*"
)

2b() {

with meson ninja

ms
nj
ni

}
