NAME="lsof"
VERS="4.99.0"
DESC="List open files for a given process"
CATG="cli util"
UPST="https://github.com/lsof-org/lsof.git"
DEPS=()

SOURCE="https://github.com/lsof-org/lsof/releases/download/$VERS/lsof-$VERS.tar.gz"
EXTRA=()

2b() {

cfg
mk
mi

}
