NAME="findutils"
VERS="4.10.0"
DESC="Programs to find and execute commands on files"

SOURCE="https://ftp.gnu.org/gnu/findutils/findutils-$VERS.tar.xz"
EXTRA=()

2b() {

b-cfg --localstatedir=/var/lib/locate
b-make
b-mi

}
