NAME="findutils"
VERS="4.10.0"
DESC="Programs to find and execute commands on files"
UPST="https://git.savannah.gnu.org/git/findutils.git"

SOURCE="https://ftp.gnu.org/gnu/findutils/findutils-$VERS.tar.xz"
EXTRA=()

2b() {

cfg --localstatedir=/var/lib/locate
mk
mi

}