NAME="ply"
VERS="3.11"
DESC="Zero-dependency python implementation of lex and yacc"
CATG="dev"
UPST="https://github.com/dabeaz/ply.git"
DEPS=(
    "python"
)

SOURCE="https://files.pythonhosted.org/packages/source/p/ply/ply-$VERS.tar.gz"
EXTRA=()

2b() {

with pip

pipb
pipi "$NAME"

}
