NAME="mtdev"
VERS="1.1.7"
DESC="Normalizes kernel multi-touch events to the slotted type B protocol"
CATG=""
UPST="http://bitmath.org/git/mtdev.git"
DEPS=()

SOURCE="https://bitmath.org/code/mtdev/mtdev-$VERS.tar.bz2"
EXTRA=()

2b() {

cfg
mk
mi

}
