NAME="mpdecimal"
VERS="4.0.0"
DESC="Arbitrary-precision decimal floating point arithmetic library"
CATG="lib"
UPST="https://www.bytereef.org/mpdecimal/index.html"
VCMD="curl -s '$UPST' | grep '$NAME-[0-9]' | cut -d- -f2 | cut -d. -f1-3"
DEPS=()

SOURCE="https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-$VERS.tar.gz"
EXTRA=()

2b() {

cfg
mk
mi

}
