NAME="wgetpaste"
VERS="2.34"
DESC="Automate pasting to a number of pastebin services"
CATG="cli utils"
UPST="https://github.com/zlin/wgetpaste.git"
DEPS=(
    "wget"
    "bash"
    "sed"
)

SOURCE="https://github.com/zlin/wgetpaste/releases/download/$VERS/wgetpaste-$VERS.tar.xz"
EXTRA=()

2b() {

install -vDm755 wgetpaste -t "$D/usr/bin/"

}
