NAME="nasm"
VERS="2.16.03"
DESC="Netwide Assembler"
CATG="lang"
UPST="https://github.com/netwide-assembler/nasm.git"
DEPS=()

SOURCE="https://www.nasm.us/pub/nasm/releasebuilds/$VERS/nasm-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

}
