NAME="jinja2"
VERS="3.1.5"
DESC="Python module implementing a simple template language"

SOURCE="https://pypi.org/packages/source/J/Jinja2/jinja2-$VERS.tar.gz"
EXTRA=()

2b() {

b-pipbuild
b-pipinstall "$NAME"

}
