NAME="jinja2"
VERS="3.1.6"
CATG="core"
DESC="Python module implementing a simple template language"
UPST="https://github.com/pallets/jinja.git"

SOURCE="https://pypi.org/packages/source/J/Jinja2/jinja2-$VERS.tar.gz"
EXTRA=()

2b() {

with pip

pipb
pipi "$NAME"

}