NAME="make"
VERS="4.4.1"
DESC="Program for generating executables and other files from source code"
UPST="https://git.savannah.gnu.org/git/make.git"
VCMD="git ls-remote --tags --refs '$UPST' | sed 's@.*/@@' | grep -Ev '[a-Z]' | grep -Ev '9[0-9]$' | tail -n1"

SOURCE="https://ftp.gnu.org/gnu/make/make-$VERS.tar.gz"
EXTRA=()

2b() {

cfg
mk
mi

}