NAME="make"
VERS="4.4.1"
DESC="Program for generating executables and other files from source code"
UPST="https://git.savannah.gnu.org/git/make.git"

SOURCE="https://ftp.gnu.org/gnu/make/make-$VERS.tar.gz"
EXTRA=()

2b() {

b-cfg
b-make
b-mi

}
