NAME="x264"
VERS="fe9e4a7f39d7a9fd208e4592238f9809d5936439"  # no releases exist
DESC="Library for encoding video streams into the H.264/MPEG-4 AVC format"
CATG="lib video"
UPST="https://code.videolan.org/videolan/x264.git"
DEPS=(
    "nasm"
)

SOURCE="https://code.videolan.org/videolan/x264/-/archive/master/x264-master.tar.bz2"
EXTRA=()

2b() {

cfg --disable-cli
mk
mi

}
