NAME="tar"
VERS="1.35"
DESC="Archive utility"
UPST="https://git.savannah.gnu.org/git/tar.git"

SOURCE="https://ftp.gnu.org/gnu/tar/tar-$VERS.tar.xz"
EXTRA=()

2b() {

FORCE_UNSAFE_CONFIGURE=1 \
b-cfg

b-make
b-mi

}
