NAME="fribidi"
VERS="1.0.16"
DESC="BIDI implementation"
CATG=""
UPST="https://github.com/fribidi/fribidi.git"
DEPS=()

SOURCE="https://github.com/fribidi/fribidi/releases/download/v$VERS/fribidi-$VERS.tar.xz"
EXTRA=()

2b() {

with meson ninja

ms
nj
ni

}
