NAME="double-conversion"
VERS="3.3.1"
DESC="Binary-decimal and decimal-binary routines for IEEE doubles"
CATG="lib"
UPST="https://github.com/google/double-conversion.git"
DEPS="cmake"

SOURCE="https://github.com/google/double-conversion/archive/v$VERS/double-conversion-$VERS.tar.gz"
EXTRA=()

2b() {

with cmake

cm -G "Unix Makefiles"
mk
mi

}
