NAME="gzip"
VERS="1.13"
CATG="core"
DESC="Programs for (de)compressing files"
UPST="https://git.savannah.gnu.org/git/gzip.git"

SOURCE="https://ftp.gnu.org/gnu/gzip/gzip-$VERS.tar.xz"
EXTRA=()

2b() {

cfg
mk
mi

}
