NAME="pixman"
VERS="0.44.2"
DESC="Pixel manipulation library for X and cairo"
UPST="https://gitlab.freedesktop.org/pixman/pixman.git"

SOURCE="https://www.x.org/releases/individual/lib/pixman-$VERS.tar.xz"
EXTRA=()

2b() {

with meson ninja

ms
nj
ni

}
