NAME="dex"
VERS="0.10.1"
DESC="Desktop entry execution utility"
CATG="utils"
UPST="https://github.com/jceb/dex.git"
DEPS=(
    "python"
)

SOURCE="https://github.com/jceb/dex/archive/refs/tags/$VERS.tar.gz"
EXTRA=()

2b() {

install -vDm755 dex -t "$D/usr/bin/"

}
#d avoid the makefile altogether
