NAME="xxhash"
VERS="0.8.3"
DESC="Extremely fast non-cryptographic hash algorithm"
UPST="https://github.com/Cyan4973/xxHash.git"

SOURCE="https://github.com/Cyan4973/xxHash/archive/refs/tags/v$VERS.tar.gz"
EXTRA=()

2b() {

b-make PREFIX=/usr
b-mi PREFIX=/usr

}
