NAME="iana-etc"
VERS="20250114"
DESC="The Internet Assigned Numbers Authority's services and protocols"

SOURCE="https://github.com/Mic92/iana-etc/releases/download/$VERS/iana-etc-$VERS.tar.gz"
EXTRA=()

2b() {

install -vDm644 -t "$D"/etc services protocols

}
