NAME="libuv"
VERS="1.50.0"
DESC="Multi-platform support library focusing on asyncio"
CATG=""
UPST="https://github.com/libuv/libuv.git"
DEPS=()

SOURCE="https://dist.libuv.org/dist/v$VERS/libuv-v$VERS.tar.gz"
EXTRA=()

2b() {

sh autogen.sh
cfg
mk
mi

}
