NAME="popt"
VERS="1.19"
DESC="Libraries for parsing command-line options"
UPST="https://github.com/rpm-software-management/popt.git"

SOURCE="https://ftp.osuosl.org/pub/rpm/popt/releases/popt-1.x/popt-1.19.tar.gz"
EXTRA=()

2b() {

b-cfg
b-make
b-mi

}
