NAME="fdk-aac"
VERS="2.0.3"
DESC="Standalone library of Android's Fraunhofer FDK AAC code"
CATG="lib audio"
UPST="https://github.com/mstorsjo/fdk-aac"
DEPS=()

SOURCE="https://github.com/mstorsjo/fdk-aac/archive/refs/tags/v$VERS.tar.gz"
EXTRA=()

2b() {

cfg
mk
mi

}
