NAME="tree"
VERS="2.2.1"
DESC="A cli utility for viewing file trees"
UPST="https://github.com/Old-Man-Programmer/tree"

SOURCE="https://github.com/Old-Man-Programmer/tree/archive/refs/tags/$VERS.tar.gz"
EXTRA=()

2b() {

b-make
make PREFIX="$D"/usr MANDIR="$D"/usr/share/man install

}
