NAME="feh"
VERS="3.10.3"
DESC="Fast, light image viewer"
CATG="img gui utils"
UPST="https://github.com/derf/feh.git"
DEPS=(
    "imlib2"
    "libpng"
    "curl"
)

SOURCE="https://feh.finalrewind.org/feh-$VERS.tar.bz2"
EXTRA=()

2b() {

mk PREFIX=/usr
mi PREFIX=/usr

}
