NAME="fd"
VERS="10.2.0"
DESC="Simple, fast, user-friendly find alternative"
CATG="utils cli"
UPST="https://github.com/sharkdp/fd.git"
DEPS=(
    "rust"
    "make"
)

SOURCE="https://github.com/sharkdp/fd/archive/refs/tags/v$VERS.tar.gz"
EXTRA=()

2b() {

with rust

mk prefix=/usr
mi prefix=/usr

}
