NAME="hwdata"
VERS="0.394"
DESC="Hardware PCI and vendor ID databases"
UPST="https://github.com/vcrhonek/$NAME.git"

SOURCE="https://github.com/vcrhonek/$NAME/archive/v$VERS/$NAME-$VERS.tar.gz"
EXTRA=()

2b() {

cfg --disable-blacklist
mi

}